---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.hypersurgery
  resources:
  - networkscopes
  - sheetexports
  - subnetclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.hypersurgery
  resources:
  - networkscopes/finalizers
  verbs:
  - update
- apiGroups:
  - aws.hypersurgery
  resources:
  - networkscopes/status
  - resourceimports/status
  - sheetexports/status
  - subnetclaims/status
  - subnets/status
  - vpcs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - aws.hypersurgery
  resources:
  - resourceimports
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - aws.hypersurgery
  resources:
  - subnets
  - vpcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
