## Append samples of your project ##
resources:
- network_v1_networkscope.yaml
- network_v1_sheetexport.yaml
- network_v1_subnetclaim.yaml
- network_v1_resourceimport.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
